version: "3.8"
services:
  auth-db:
    container_name: auth-db
    build: docker/images/db
    volumes:
      - auth_data:/var/lib/postgresql/data/
    networks:
      - auth

  auth-api:
    container_name: auth-api
    build:
      context: ./src/auth-api
      dockerfile: ../../docker/images/javascript/Dockerfile
    networks:
      - auth
      - common
    expose:
      - "18080"
    environment:
      - USE_DEV_MODE
      - PORT=18080

  bl-db:
    container_name: bl-db
    build: docker/images/db
    volumes:
      - bl_data:/var/lib/postgresql/data/
    networks:
      - bl

  bl-api:
    container_name: bl-api
    build:
      context: ./src/bl-api
      dockerfile: ../../docker/images/javascript/Dockerfile
    networks:
      - bl
      - common
    expose: 
      - "8080"
    environment:
      - USE_DEV_MODE
      - PORT=8080
      - SWAGGER_PORT=8081
      - DATABASE_URL=postgresql://sd:sd@bl-db:5432/sd?schema=public

  importer:
    container_name: importer
    build:
      context: ./src/importer
      dockerfile: ../../docker/images/javascript/Dockerfile
    networks:
      - bl
    volumes:
      - ./docker/volumes/importer/movies:/data # <-- A MÁGICA ESTÁ AQUI: Ligação direta à tua pasta!
    environment:
      - USE_DEV_MODE

  frontend:
    container_name: frontend
    build:
      context: ./src/web
      dockerfile: ../../docker/images/javascript/Dockerfile
    networks:
      - common
    expose: #expose 70 port for frontendqq
      - "3000"
    environment:
      - USE_DEV_MODE
      - PORT=3000
      # - REACT_APP_API_URL=http://localhost:$BL_API_PORT
      - WDS_SOCKET_PORT=0
      - WDS_SOCKET_PORT=0
      - REACT_APP_BL_API_URL=${REACT_APP_BL_API_URL}
      - REACT_APP_AUTH_API_URL=${REACT_APP_AUTH_API_URL}

networks:
  common:
    driver: bridge
  auth:
    driver: bridge
  bl:
    driver: bridge

volumes:
  auth_data:
  bl_data:
  importer_data:
